name: Trivy Vulnerability Scan

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify phase
        run: mvn clean --batch-mode --update-snapshots dependency:copy-dependencies -DoutputDirectory=./target/lib
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '/github/workspace/dispatch-controller-service/target/lib'
          format: 'table'
          timeout: '10m0s'
          exit-code: '1'
          